import { Roboto } from 'next/font/google'
import './globals.css'
import Header from './Components/Layout/Header'
import Footer from './Components/Layout/Footer'

const roboto = Roboto({ subsets: ['latin'], weight:["300", "400", "500", "700"]})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className='max-w-4xl mx-auto'>
          <Header/>
        </main>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
